#!/usr/bin/env bash

problem="$1"

origdir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

cd /tmp
if [ ! -d ds_challenge_fall2014 ]
then
  echo "checkout repository"
  git clone https://github.com/comsysto/ds_challenge_fall2014.git
fi

cd ds_challenge_fall2014/
git pull --rebase
grep ":arrow_right:" ${problem}/README.md | cut -d' ' -f2- > tmp && mv -f tmp ${problem}/README.md

tar -zcf ${problem}.tar.gz ${problem}/README.md ${problem}/docs/*.pdf ${problem}/out ${problem}/src
mv ${problem}.tar.gz $origdir

git co .

cd /tmp

echo "Packed $origdir/${problem}.tar.gz"
