#!/usr/bin/env bash

problem="$1"

origdir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

cd /tmp
git clone --quiet https://github.com/comsysto/ds_challenge_fall2014.git
cd ds_challenge_fall2014/
grep ":arrow_right:" ${problem}/README.md | cut -d' ' -f2- > tmp && mv -f tmp ${problem}/README.md

tar -zcf ${problem}.tar.gz ${problem}/README.md ${problem}/docs/*.pdf ${problem}/out ${problem}/src
mv ${problem}.tar.gz $origdir
cd /tmp
rm -rf ds_challenge_fall2014

echo "Packed $origdir/${problem}.tar.gz"
